spring:
  application:
    name:
      "Infraxus"

  config:
    import: optional:file:env/infraxus.env[.properties]

  cassandra:
    contact-points: 127.0.0.1
    port: 9042
    keyspace-name: infraxus
    schema-action: create_if_not_exists
    local-datacenter: datacenter1

jenkins:
  url: ${JENKINS_URL}
  username: ${JENKINS_USERNAME}
  token: ${JENKINS_TOKEN}

docker:
  host: ${DOCKER_HOST}
  tls-verify: ${DOCKER_TLS_VERIFY}

logging:
  level:
    root: INFO
    org.springframework.data.cassandra.core.cql: DEBUG
    com.datastax.oss.driver.internal.core.tracker.RequestLogger: DEBUG
    com.datastax.oss.driver: INFO
