global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Docker Service Discovery for dynamically created containers
  - job_name: 'docker-containers'
    # 이 부분이 핵심입니다. Docker 소켓을 통해 컨테이너를 찾습니다.
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      # "prometheus.scrape=true" 라벨이 붙은 컨테이너만 수집 대상으로 삼습니다.
      - source_labels: [__meta_docker_container_label_prometheus_scrape]
        action: keep
        regex: true
      # 컨테이너 이름을 "instance" 라벨로 사용합니다.
      - source_labels: [__meta_docker_container_name]
        target_label: instance
        replacement: "$1"
      # 컨테이너의 네트워크 IP와 "prometheus.port" 라벨을 조합하여 접속 주소를 만듭니다.
      - source_labels: [__address__, __meta_docker_container_label_prometheus_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
